apiVersion: template.openshift.io/orange
kind: Template
metadata:
  annotations:
    description: A template to deploy the Antennas Incident Service
    iconClass: icon-quarkus
    tags: quarkus,service
  name: incidents-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.quarkus.io/build-timestamp: 2022-05-15 - 08:38:34 +0000
    labels:
      app.kubernetes.io/name: antennas-incident
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
    name: antennas-incident
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 8080
    selector:
      app.kubernetes.io/name: antennas-incident
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      app.quarkus.io/build-timestamp: 2022-05-15 - 08:38:34 +0000
    labels:
      app.kubernetes.io/name: antennas-incident
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
    name: antennas-incident
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: antennas-incident
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    template:
      metadata:
        annotations:
          app.quarkus.io/build-timestamp: 2022-05-15 - 08:38:34 +0000
        labels:
          app.kubernetes.io/name: antennas-incident
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                key: apikey
                name: incidents-secret
          image: quay.io/sebastienblanc0/antennas-incident:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: antennas-incident
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
- apiVersion: v1
  kind: Secret
  metadata:
    name: incidents-secret
  stringData:
    apikey: secret
  type: Opaque
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: antennas-incident
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: antennas-incident
      weight: 100
    wildcardPolicy: None
